# Generated by Django 5.2.11 on 2026-04-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0002_alter_detectionhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
