# Generated by Django 5.2.11 on 2026-04-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0003_detectionhistory_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionhistory',
            options={'ordering': ['-date']},
        ),
    ]
